# Generated by Django 3.1.6 on 2021-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210220_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='createdby',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
