# Generated by Django 3.1.6 on 2021-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdby',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
