# Generated by Django 3.1.6 on 2021-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addedby',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
