# Generated by Django 3.1.6 on 2021-02-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_reg',
        ),
    ]
