# Generated by Django 3.1.6 on 2021-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_product_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='addedby',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='addedby',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
